first_number = int(input("Enter first number: "))
second_number = int(input("Enter second number: "))
third_number = int(input("Enter third number: "))
numbers = (first_number, second_number, third_number)
print(sorted(numbers))